---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.10
  - name: centos-6.6

suites:
  - name: default
    run_list:
      - recipe[base-settings::default]
    attributes:
      openssh: 
        server:
          password_authentication: "no"
          permit_root_login: "no"
    data_bags_path: test/data_bags
